# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sS <- function(v) {
    .Call('symAlgebra_sS', PACKAGE = 'symAlgebra', v)
}

sN <- function(v) {
    .Call('symAlgebra_sN', PACKAGE = 'symAlgebra', v)
}

sSymboloperator_plus <- function(x, y) {
    .Call('symAlgebra_sSymboloperator_plus', PACKAGE = 'symAlgebra', x, y)
}

sSymboloperator_minus <- function(x, y) {
    .Call('symAlgebra_sSymboloperator_minus', PACKAGE = 'symAlgebra', x, y)
}

sSymboloperator_times <- function(x, y) {
    .Call('symAlgebra_sSymboloperator_times', PACKAGE = 'symAlgebra', x, y)
}

sSymboloperator_divide <- function(x, y) {
    .Call('symAlgebra_sSymboloperator_divide', PACKAGE = 'symAlgebra', x, y)
}

sSymboloperator_power <- function(x, y) {
    .Call('symAlgebra_sSymboloperator_power', PACKAGE = 'symAlgebra', x, y)
}

sSymboloperator_equal <- function(x, y) {
    .Call('symAlgebra_sSymboloperator_equal', PACKAGE = 'symAlgebra', x, y)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('symAlgebra_RcppExport_registerCCallable', PACKAGE = 'symAlgebra')
})
