# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sAlg_fromString <- function(v) {
    .Call('symAlgebra_sAlg_fromString', PACKAGE = 'symAlgebra', v)
}

sAlg_fromDouble <- function(v) {
    .Call('symAlgebra_sAlg_fromDouble', PACKAGE = 'symAlgebra', v)
}

sAlg_fromInt <- function(v) {
    .Call('symAlgebra_sAlg_fromInt', PACKAGE = 'symAlgebra', v)
}

sAlg_plus <- function(x, y) {
    .Call('symAlgebra_sAlg_plus', PACKAGE = 'symAlgebra', x, y)
}

sAlg_minus <- function(x, y) {
    .Call('symAlgebra_sAlg_minus', PACKAGE = 'symAlgebra', x, y)
}

sAlg_times <- function(x, y) {
    .Call('symAlgebra_sAlg_times', PACKAGE = 'symAlgebra', x, y)
}

sAlg_divide <- function(x, y) {
    .Call('symAlgebra_sAlg_divide', PACKAGE = 'symAlgebra', x, y)
}

sAlg_power <- function(x, y) {
    .Call('symAlgebra_sAlg_power', PACKAGE = 'symAlgebra', x, y)
}

sAlg_equal <- function(x, y) {
    .Call('symAlgebra_sAlg_equal', PACKAGE = 'symAlgebra', x, y)
}

sAlg_ToC <- function(x) {
    .Call('symAlgebra_sAlg_ToC', PACKAGE = 'symAlgebra', x)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('symAlgebra_RcppExport_registerCCallable', PACKAGE = 'symAlgebra')
})
